// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZEpbOp9ReNpAydjY61ucbZqEEYEOFEx4',
    appId: '1:1010017474459:web:a3ab85937c700acc86733e',
    messagingSenderId: '1010017474459',
    projectId: 'lifelens-5bbd7',
    authDomain: 'lifelens-5bbd7.firebaseapp.com',
    storageBucket: 'lifelens-5bbd7.firebasestorage.app',
    measurementId: 'G-82F8QCX25L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REDACTED_PRIVATE_API_KEY',
    appId: '1:1010017474459:android:900bd2d1bb92e75a86733e',
    messagingSenderId: '1010017474459',
    projectId: 'lifelens-5bbd7',
    storageBucket: 'lifelens-5bbd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQyRoRHJX9xxrflO2lNsPA1lCiw8Sw1wI',
    appId: '1:1010017474459:ios:f8f34d81b28e69c586733e',
    messagingSenderId: '1010017474459',
    projectId: 'lifelens-5bbd7',
    storageBucket: 'lifelens-5bbd7.firebasestorage.app',
    iosClientId: '1010017474459-9gnonm0l38of51al7s7cq2974tp6l770.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifelens',
  );
}
