// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZEpbOp9ReNpAydjY61ucbZqEEYEOFEx4',
    appId: '1:1010017474459:web:a3ab85937c700acc86733e',
    messagingSenderId: '1010017474459',
    projectId: 'lifelens-5bbd7',
    authDomain: 'lifelens-5bbd7.firebaseapp.com',
    storageBucket: 'lifelens-5bbd7.firebasestorage.app',
    measurementId: 'G-82F8QCX25L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAds1Vuln1wEMuxfbAwR_9i2ziGEmBLYI0',
    appId: '1:506558902187:android:c4758858ec1cc8520cacee',
    messagingSenderId: '506558902187',
    projectId: 'tisra-netra',
    storageBucket: 'tisra-netra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtu4c2qupQdWcocYjM6K8tvEw1azfYvwc',
    appId: '1:506558902187:ios:e366aebe461a26c20cacee',
    messagingSenderId: '506558902187',
    projectId: 'tisra-netra',
    storageBucket: 'tisra-netra.firebasestorage.app',
    iosClientId: '506558902187-s70f6f0cqb8svjdk781813c0quajhuak.apps.googleusercontent.com',
    iosBundleId: 'com.example.percive',
  );

}